version: "3.7"

services:
  server:
    image: nginx:stable-alpine
    depends_on:
      - php
      - mysql
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    networks:
      - lara-search
  
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    env_file:
      - ./mysql/.env
    networks:
      - lara-search
  
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - lara-search

  composer:
    image: composer:2
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - lara-search
  
  node:
    image: node:16
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - lara-search
    
  artisan:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['/var/www/html/artisan']
    networks:
      - lara-search 
  meilisearch:
    image: getmeili/meilisearch:latest
    # platform: linux/x86_64
    ports:
        - 7700:7700
    volumes:
        - ./meilisearch/data:/data.ms
    networks:
        - lara-search

networks:
  lara-search:
    